name: nitaku
description: A new Flutter project.
publish_to: 'none' # パッケージを公開しない場合はこの行を残す

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  google_sign_in: ^6.2.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.2
  logging: ^1.3.0
  flutter_dotenv: ^5.2.1
  uuid: ^4.5.1
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
  assets:
    - .env
    