// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCztqb6uYHjN1QKvTuADxEbdpM6ZVN5LdE',
    appId: '1:1058282353559:web:c32986c0de79a6eabd4ad2',
    messagingSenderId: '1058282353559',
    projectId: 'jp-takaakiu-nitaku',
    authDomain: 'jp-takaakiu-nitaku.firebaseapp.com',
    storageBucket: 'jp-takaakiu-nitaku.firebasestorage.app',
    measurementId: 'G-H4RBBT2CTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFb2croRrX8Og7IeQTlD4F72l7V-SKMtM',
    appId: '1:1058282353559:android:9e851af16c6fcc15bd4ad2',
    messagingSenderId: '1058282353559',
    projectId: 'jp-takaakiu-nitaku',
    storageBucket: 'jp-takaakiu-nitaku.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk0SeZOZDAor1O60lteAnl80bRgYCvYUI',
    appId: '1:1058282353559:ios:065728edac2e9d3fbd4ad2',
    messagingSenderId: '1058282353559',
    projectId: 'jp-takaakiu-nitaku',
    storageBucket: 'jp-takaakiu-nitaku.firebasestorage.app',
    iosClientId: '1058282353559-tg2njs530c4fida4stfnk7dbv4iha49l.apps.googleusercontent.com',
    iosBundleId: 'jp.takaakiu.nitaku',
  );
}
